services:
  backend:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    container_name: servicos-backend
    ports:
      - "25000:25000"
    restart: unless-stopped

  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    container_name: servicos-frontend
    ports:
      - "8080:8080"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:25000
    restart: unless-stopped