services:
  backend:
    build:
      context: .
      dockerfile: back_end/Dockerfile
    container_name: servicos-backend
    ports:
      - "25000:25000"
    restart: unless-stopped

  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    container_name: servicos-frontend
    ports:
      - "8080:80"
    restart: unless-stopped